### ISSUE TITLE
Fix a bunch of nits

### ISSUE THREAD

**Issue by 0vercl0k** [0vercl0k/kdmp-parser#21]
- [x] Image link in the README.md for Python is busted
- [x] Global README needs a refresh to point at pip, new build instructions, etc

**Comment by hugsy** [comment]
Also broken/missing:
 - [ ] OSX builds work fine
 - [ ] Remove the part about `builder.py`
 - [ ] Reference to the old Python API
 - [ ] Invalid badge link (should be opening the Actions on click - I suppose)
